### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by mjfee** [hunterjm/futgui#100]
I believe I am doing everything right, but getting this error logging in. Login screen stays blank after attempt.
![image](https://cloud.githubusercontent.com/assets/10869967/19174631/426b0daa-8bfe-11e6-971e-fd0973393a34.png)

**Comment by hunterjm** [comment]
Are you able to successfully login here: https://www.easports.com/fifa/ultimate-team/web-app

**Comment by donmassimo** [comment]
I had the same error. Your transfermarket is locked you can check it on the web app.

Anyone know how to unlock the market? It says you must play fut17 to unlock the market.

I played 30 games on ps4 it is also locked

**Comment by hunterjm** [comment]
You need to play a number of games over multiple days. It took me a week to unlock my secondary.

**Comment by donmassimo** [comment]
Ok thank you hunter:)
