### ISSUE TITLE
Enhancement request : Purchassed mode 59°

### ISSUE THREAD

**Issue by Mglt-b** [hunterjm/futgui#101]
Hello,

I don't know if it's possible to add a "purchassed mode 59°", but some players set low price on "BIN" players, and we can track it ?

When we go in this mode, the bot will : 

we set a max BIN price
search only players with time 55min to 1 hour

**Comment by hunterjm** [comment]
This is what the "BIN Snipe" setting does. You are going to make more money bidding on players though.
