### ISSUE TITLE
Trade not found

### ISSUE THREAD

**Issue by rafaelsgc** [hunterjm/futgui#105]
Hey!

I'm having an issue, as on the log I'm receiving the following message:

_Trade not found - baseId: 201400_

Not sure what this means.

Great work with the app btw.

**Comment by Faruk-S** [comment]
I don't know why but yesterday I've same issue. Today it's gone.

**Comment by Mardaneus86** [comment]
Something's wrong with Rafinha on your watch list or transfer list (baseId 201400 is him). Removing that specific player from the list is a workaround. Not sure what's causing it though.

**Comment by rafaelsgc** [comment]
It seems that this happened because i had a bid on this player, and then I quit bidding and returned to player search. When I started bidding again, it seems that it's trying to bid on a trade that doesn't exists anymore... not sure if this is the real cause though

**Comment by Diamir9** [comment]
Hunterjm, a big thank you for creating this app.
I have the same issue but with base id 199451. Can I check by myself which player this is?

**Comment by hunterjm** [comment]
You can lookup the ID in here: http://cdn.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/web/players.json

**Comment by Diamir9** [comment]
Clearing my Transfer Target's list helped
