### ISSUE TITLE
crashes after player search 

### ISSUE THREAD

**Issue by hyoussef** [hunterjm/futgui#106]
Hello

it is crashing after player search every time.
Platform MacOS Sierra.

**Comment by Paxaw** [comment]
Hi there, 
It is happening exactly the same for me... 
MacOS Sierra here as well.

EDIT:
Tested with windows 8 and it reports this error:

UnknownError: None ({'reason': '', 'debug': '', 'string': '', 'code': '494'})

any suggestion?

RE-EDIT: I found the solution here: Why when I start to buy players you tell me so in the console? #75
Transfer market it isn't availeable for me yet.

**Comment by Paxaw** [comment]
Tested with windows 8 and it reports this error:

 UnknownError: None ({'reason': '', 'debug': '', 'string': '', 'code': '494'})

any suggestion?

**Comment by jchengl** [comment]
#67 That should temporary fix it..

**Comment by hyoussef** [comment]
thanks the workaround fixes the issue.
