### ISSUE TITLE
Bid errors

### ISSUE THREAD

**Issue by mjfee** [hunterjm/futgui#110]
I keep seeing these over and over. Could this mean I was failing to place bids? I didn't seem to win any player.
![image](https://cloud.githubusercontent.com/assets/10869967/19218543/abaa945c-8dca-11e6-83eb-f2cbcc3c9b14.png)

**Comment by moathabdulhadi** [comment]
any one know to fix this ?

**Comment by umair-io** [comment]
These errors I suspect are due to the "Transfer Targets" section being full of won/expired items. Any plans to add feature to clear it? Thanks

**Comment by moathabdulhadi** [comment]
i think you list items , try to remove them and only list players, i face this before and i only list players and its work again like charm ;)

**Comment by mjfee** [comment]
Thanks for the responses guys. Odd thing is, my targets list was not full, in fact it may have been empty.

**Comment by hunterjm** [comment]
Your targets had a non-player card in it.  See https://github.com/hunterjm/futgui/issues/25
