### ISSUE TITLE
General tutorial? [Request]

### ISSUE THREAD

**Issue by valik140795** [hunterjm/futgui#117]
Hi

Im personally super inexperienced in the ultimate team trading and I'm finding difficulties locating some sort of guide or a tutorial on utilisation techniques for this program. Ive tried googling for forums and other third party sources which would help me get familiar with all the options before i start bidding and potentially loose coins due to lack of knowledge. Any help would be appreciated.

Thanks in advance.

**Comment by Mglt-b** [comment]
Have you see that ?

https://github.com/hunterjm/futgui/issues/16
