### ISSUE TITLE
Freeze after login

### ISSUE THREAD

**Issue by lifez** [hunterjm/futgui#126]
i got freeze after click login. I already try on 3 emulator

is it because new update ?

https://puu.sh/rIGlq/0b4869bcfd.png

**Comment by lifez** [comment]
It worked after clean install

**Comment by leonwu127** [comment]
Hi @lifez , I have the same situation here. What do you mean by clean install?

**Comment by lifez** [comment]
@leonwu127 Delete all file and reinstall it
