### ISSUE TITLE
I still got this error when trying to login "AttributeError: 'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by marlonespindola** [hunterjm/futgui#135]
i have the latest source from this project and still got this error.. heres my pip list

![pip_list](https://cloud.githubusercontent.com/assets/16193729/19461727/077188f2-94c6-11e6-8a21-8e3f21206e38.jpg)

please some help...

**Comment by hunterjm** [comment]
Remove all items from your transfer list and try again.

**Comment by marlonespindola** [comment]
i have removed all items and still got the same message...
funny thing is that with the latest release v1.1.1 the program works, but running with the  python i got the message...

**Comment by marlonespindola** [comment]
Problema solved :)
