### ISSUE TITLE
InternalServerError: (500) After I won a player on the market

### ISSUE THREAD

**Issue by stijnbastiaansen** [hunterjm/futgui#137]
Everytime I win a player on the market I get an InternalServerError: (500); like this:
`2016-10-18 11:11:06    Updating watched items...
2016-10-18 11:11:09    Auction Won: 2000 on Gaël Clichy
2016-10-18 11:11:20    InternalServerError:  (500)
2016-10-18 11:11:28    Updating watched items...
2016-10-18 11:11:28    Stopped bidding...`

What am I doing wrong?

**Comment by lolol1236** [comment]
That's a temporary ban

**Comment by alexeyvolodin** [comment]
you can relogin and change emulation type

**Comment by stijnbastiaansen** [comment]
Thanks for the reactions guys, but it wasn't a temporary ban. I could bid on the webapp/android and ios. 
The problem was with a player. I changed the player list with other players and it is working again. 

So if anyone has the same problem when you don't have a temporary ban, change the players you are bidding on and it should work again.
