### ISSUE TITLE
Cannot run on Windows 10

### ISSUE THREAD

**Issue by JustinRZJ** [hunterjm/futgui#14]
When I started it, it says" Fifa auto buyer returned -1", have tried different administrator and compatibility settings, still not working. Please fix it. Thank you.

**Comment by Faruk-S** [comment]
I have same problem. 
win 10 64 bit

**Comment by A-VORONKIN** [comment]
same problem

**Comment by hunterjm** [comment]
That's interesting.  I ran the build script on Window's 10 64-bit.  Do you get this error as soon as you attempt to open the app, or after you start bidding?

**Comment by Faruk-S** [comment]
As soon as attemp to open. 
http://tinypic.com/r/14o6tlv/9

**Comment by hunterjm** [comment]
Give v0.6.1-beta a try.  I didn't do anything really to fix it, but if other versions worked and 0.6.0 did not, it may work again this time.

**Comment by JANA73** [comment]
Same prob

**Comment by Faruk-S** [comment]
v0.6.1-beta has the same error.

**Comment by aludvigsen** [comment]
Its not just Win 10, running Win 8.1 here, I get the same error.

**Comment by hunterjm** [comment]
I just uploaded a new version of 0.6.1 that launches a console window which should have some more debugging information.  Can one of you [download it](https://github.com/hunterjm/futgui/releases/download/v0.6.1-beta/FIFA.16.Auto.Buyer-v0.6.1-Windows-Console.zip) and paste the console output in here?

**Comment by A-VORONKIN** [comment]
https://gyazo.com/e831d7d8d5c6e121e8bc84dadc5c7e0c

**Comment by fabianofrancesconi** [comment]
Uhm was it working with version 0.5?

**Comment by hunterjm** [comment]
Yeah, it was a part of the PEP8 changes @oczkers made.  Should be fixed in v0.6.2: https://github.com/hunterjm/futgui/releases/tag/v0.6.2-beta
