### ISSUE TITLE
BIN Snipe fuctionnot working

### ISSUE THREAD

**Issue by Leikauf** [hunterjm/futgui#143]
I used the program once with BIN Snpie fuction it worked, but now I start  the program set the players auto prizes, and after the don't search anything. What could be the problem? Without
(Win 10 64bit, PS4, and i use the v1.1.1 Beta version) 
Thanks the program to @hunterjm and in advance for your answer!

**Comment by hunterjm** [comment]
It won't snipe anything is there is nothing to snipe. So long as bid cycles keep incrementing, it's working.
