### ISSUE TITLE
Relist Strategy

### ISSUE THREAD

**Issue by hunterjm** [hunterjm/futgui#15]
I have a question for everyone here. Should I re-list expired items for a loss if the price has changed so we can clear inventory to hopefully make that money back, or should I re-list at the initial price? I'm leaning towards re-listing for a loss.

**Comment by jchengl** [comment]
I'd stay with the initial price.

**Comment by aludvigsen** [comment]
I started to develop a simple "relist app" last week. The main idea is to relist every hour of course when the items have expired, but also track how many times each item has been listed. If an item has been listed, say X number of times, I decrease the listing price to get rid of that item.

**Comment by hunterjm** [comment]
I like that idea @aludvigsen.  Of course I could always make it another setting.  I've noticed that if a price drops more than 10%, it doesn't ever really come back up, which means you could have a lot of players sitting for a long time, which limits the amount of players you can move.

The big question: Is it worth having a full tradepile to keep from having a loss, or should you just take the small loss and keep moving on (maybe make it back in a couple of hours)?

**Comment by aludvigsen** [comment]
I definitely agree that having players sitting in the tradepile for a long time isn't profitable. I also think a small loss for that item is worth it, to clear space. But it depends on the type of tradingstyle aswell. If you buy at 90%, and sell at 100%, you would probably profit from clearing that tradepile quickly. But if you sell at ~125%, then you would probably need to give that item some more time. In other words, a setting parameter would probably be best. ;)

**Comment by aftershock9** [comment]
I'm in agreement with @aludvigsen. Parameter setting would be great.

**Comment by hunterjm** [comment]
Done (https://github.com/hunterjm/futgui/commit/b83d6c0a6b865aaa9403958d42fde1395004c6eb)

As a side note, I'm starting to wish I used something other than tkinter.  It's hard to make things pretty.  Then again, I'm no designer anyway, so it probably wouldn't look much better in anything else :)

**Comment by fabianofrancesconi** [comment]
I think that maybe Qt would be a better choice for the UI. It is fairly simple to use and also cross-platform.
