### ISSUE TITLE
Program crashes after first "Updating prices" round

### ISSUE THREAD

**Issue by Fotospecht** [hunterjm/futgui#151]
I run the Futgui from the python3.5 comandline on Mac OSX Sierra.

Most of the time the program crashes after the first round of updating prices
and sometimes it takes 5-6 times to get the program running properly and past the price check.
When the first price check is complete and the program eventually continues, all the following price checks run fine and the program is running for days without problems.
You can even go back to the first login-screen, then login and start the bidding and first price check round again without any further problems.

I suspect the problem has something to do with the first population of the top right list of the players or a similar step that is executed only after the first price check is done. It might also be the case that one of the "CALayer position contains NaN: [nan 0]" errors is not catched.

**Comment by Fotospecht** [comment]
Crashed Thread:        0  Dispatch queue: com.apple.os.log

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000010401587a
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

**Comment by Fotospecht** [comment]
Problem has suddenly been resolved.

**Comment by darfinx** [comment]
i think it related with halloween cards

Get Outlook for iOS

```
    _____________________________
```
