### ISSUE TITLE
To many errors warching trades

### ISSUE THREAD

**Issue by artemiokost** [hunterjm/futgui#158]
All the time kick me off after watching player. In stats: "To many errors watching trades. Please re-login". Login information is correct wtf
![sht](https://cloud.githubusercontent.com/assets/19749384/20106853/1435dbac-a609-11e6-8aa6-a3effae9e6cf.png)
?!

**Comment by martijnbrands** [comment]
@Luckyshroom Probably you need to reduce your RPM. Mine is on 15.

**Comment by mestesso93** [comment]
@martijnbrands excuse me, but mine RPM is 7 and i have only 1 player in list. I have set price autoupdate without bin snipe and i get error 500. What's wrong in my configuration? I want leave the pc when the bot work.. thank you!

**Comment by martijnbrands** [comment]
@mestesso93 Change the emulation type if that's not working try to bid on another player.

**Comment by artemiokost** [comment]
@martijnbrands, thks your advise work! Question is over.
