### ISSUE TITLE
Buy now

### ISSUE THREAD

**Issue by davkh** [hunterjm/futgui#161]
Hi mate,

Will be nice if you can add buy now option as well, not just bidding. Also Will be nice not only but players, but also consumables: contracts.

**Comment by martijnbrands** [comment]
@davkh There is already a buy now option. 
When checked BIN snipe it will make the program only purchase BIN items at or below your Max bid price, with no bidding at all. If you unchecked it wil bid on players and also buy it now if there is a player on the market for your Max bid price. _Correct me if I'm wrong_

**Comment by hunterjm** [comment]
Correct.

**Comment by davkh** [comment]
What about consumables?
