### ISSUE TITLE
Error 500 - Possible Solution

### ISSUE THREAD

**Issue by mestesso93** [hunterjm/futgui#163]
Hi all! To begin, thanks for this wonderful program.
I have try this autobidder and i noticed that i get error 500 when my auction end without any offer. This error appear when the program relist the player manually. I think this error is given by manually relisting (when the items are 5 or more). Maybe the solution at this problem is edit this function in "reassigns all" as the web-app with one button and not one by one.

Sorry for my bad english, i used an online translator!

**Comment by hunterjm** [comment]
The "Same re-list price" option does that. The only problem is then you are unable to change the price of the player if the market has shifted.

Either way, it's a temporary ban on selling players and should go away with switching the emulation type or waiting.
