### ISSUE TITLE
online gamertags

### ISSUE THREAD

**Issue by celioreyes** [hunterjm/futgui#175]
Hey guys!

I wanted to play against some of you to see the kind of teams that you have built using this bidder. I'm on xboxone. Would some of you be willing to play ?

**Comment by anthonymac** [comment]
Are you a cop?

**Comment by hunterjm** [comment]
Haha! Nah, he's a co-worker of mine. Helping out a little on the next version of this AB.

**Comment by celioreyes** [comment]
@anthonymac i just want to see the teams that are being build by the users of the AB! @hunterjm has put a lot of work into the next version of this AB and I want to play FIFA users that have good teams!

**Comment by anthonymac** [comment]
just checkin' lol. I appreciate all the hard work you are putting in. I'm afraid i cannot help you re: your request, as my squad is fairly average. i spent my profits trying to get the SBC Lacazette.

**Comment by celioreyes** [comment]
@anthonymac i have a pretty basic team too, I haven't used the AB for FIFA17 yet. 
This is my team. 
<img width="599" alt="screen shot 2017-01-16 at 1 59 03 pm" src="https://cloud.githubusercontent.com/assets/8867614/21995668/0dbac988-dbf4-11e6-9108-a5197656eb7e.png">

**Comment by anthonymac** [comment]
[
![20170116_234733](https://cloud.githubusercontent.com/assets/24725226/22001562/53147fb8-dc46-11e6-9e44-6700fb2415fe.png)
](url)

**Comment by anthonymac** [comment]
i got this mostly from just earning coins the hard way. the AB helped me get Douglas Costa and Leno. and the rest i blew on cocaine and hookers AKA the SBC challenges
