### ISSUE TITLE
Which players and what price? And a little help…

### ISSUE THREAD

**Issue by enricostaite** [hunterjm/futgui#180]
Has anyone got an idea of who are the best players to use and the best prices. Or is there a way of all the players and prices to be automatically placed in? Also for some reason I can't get the iOS or android emulate part to work, it brings up "Error logging in: None (UnknownError). Help please?

**Comment by hunterjm** [comment]
I'm no longer maintaining this version of the Auto Buyer.  Please check out http://fifa.hunterjm.com and https://github.com/hunterjm/fifa-autobuyer
