### ISSUE TITLE
Exception thrown when searching for Gomis (Silver Keeper): TypeError: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by aftershock9** [hunterjm/futgui#19]
Came across a minor issue:

This player, http://www.futbin.com/16/player/10316/gomis, causes the following exception to be thrown.  
![fut](https://cloud.githubusercontent.com/assets/6708705/11510713/c4fef1bc-986d-11e5-85a6-55b9ecedcec8.png)

This results in his price not being set. 

Application Version: 0.7.0

**Comment by hunterjm** [comment]
Looks like there aren't any of him on the market?!?  Weird.  I fixed it in the master branch, but I won't release it until the next update.
