### ISSUE TITLE
Anomaly on listing price

### ISSUE THREAD

**Issue by shuohan27** [hunterjm/futgui#23]
Jason, here's another anomaly on the listing price point.  David Silva bought for very cheap but also sold for much cheaper than it should have been listed for.  This is on 0.7.1 with "Same Price Relist $" unchecked.  See attached log:
## 

In case I forgot to mention, your program is EXCELLENT now after the 7.0 release, even with any bugs present.  Thank you!

**Comment by shuohan27** [comment]
I apologize, I mixed up Willian with David Silva (Willian has Silva in his name).  Closing issue...

**Comment by hunterjm** [comment]
No problem!
