### ISSUE TITLE
Endless loop of manually listing a player

### ISSUE THREAD

**Issue by aftershock9** [hunterjm/futgui#28]
If you have a player that has expired which doesn't exist in your bid list, then the AB log will endlessly display a message, "Manually listing 1 player". It seems that if the player that its trying to list doesn't exist in the player bid list, this endless loop happens.

**Comment by fabianofrancesconi** [comment]
I have already fixed that in my branch.

**Comment by aftershock9** [comment]
Awesome and thanks for the prompt response :)
