### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OthonGBR** [hunterjm/futgui#31]
The program is locking and opening this error on the screen:

![error](https://cloud.githubusercontent.com/assets/14895784/11737147/8db800f2-9fbd-11e5-9f44-688b84a2d080.png)

This error did not occur in the previous version. But now he began to be caught in "Start Biding" and the program takes no action!

I'm using the latest version of Perl

**Comment by OthonGBR** [comment]
Sorry. I had not seen who answered me and open another doubt. May close.

**Comment by hunterjm** [comment]
Closed at request of author.
