### ISSUE TITLE
Mobile login error

### ISSUE THREAD

**Issue by aftershock9** [hunterjm/futgui#33]
The mobile emulation for the latest release (v0.7.2) is returning the following error: Error logging in: None (UnknownError)

I have tried both Andriod and iOS.

**Comment by hunterjm** [comment]
Go back to 0.7.1 and see if it still works.  I made the update because 0.7.1 stopped working for me on mobile.

**Comment by Faruk-S** [comment]
Is mobile login still available? When will you fix that?
