### ISSUE TITLE
login

### ISSUE THREAD

**Issue by joaopedromello** [hunterjm/futgui#34]
i cant login  i put all the informations and the access code but it doesn't Work.It appears:
Error logging in: None (UnknowError)

**Comment by Faruk-S** [comment]
Android and ios login still not working for me

**Comment by aftershock9** [comment]
Yes, I have been experiencing this issue which has been reported in a few places. Hunter has said that he is quite busy with work till christmas, so in the mean time use the PC emulation till he has a moment to investigate and resolve these issues.

**Comment by Faruk-S** [comment]
Shuoran from elitepvpers wrote a repacked version of 7.02 works for android/ios login. I don't know how to do that so if you repacked 7.02 please share us till hunter resolve the issue.
