### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by DarkVador101** [hunterjm/futgui#36]
I am a .net developer with some Python experience and I am new to this type of automation. How is the flash automated through requests. I am a little lost in that direction. I thought it could only be possible with subimage searches and coordinate mouse click messages since the web app is flash based and not HTML based. any explanation is appreciated.

**Comment by fabianofrancesconi** [comment]
The flash application developed by EA is underneath using a RESTful API. The [fut](https://github.com/oczkers/fut) project provides this API as the result of a reverse engineering by his author.

This project thus uses this fut API to make the requests (there is no subimage search and mouse click at all)

**Comment by hunterjm** [comment]
See https://github.com/oczkers/fut for the underlying project that this UI takes advantage of.
