### ISSUE TITLE
Login Mistake

### ISSUE THREAD

**Issue by agvingut** [hunterjm/futgui#40]
If you have two user, for example, pepe@gmail.com and pepe@outlook.es, the login form not recognizes the second that your enter, always login in ea with the first that you use. Internally the application use two different account but against ea, only use one, the first that did use

**Comment by aftershock9** [comment]
The Autobuyer (AB) currently only uses one login. if you want to switch login details, please delete "login.json" file in the following location: C:\Users{your-PC-username}.config\futgui\ [replace {your-PC-username} with your PC login information] 

I am not sure whether multiple logins is on the horizon for hunters enhancement.

**Comment by agvingut** [comment]
Thanks, but i'm mac user and i don't found  login.json

**Comment by agvingut** [comment]
In mac system login.json file is in /Users/[username]/.config/futgui/login.json

**Comment by hunterjm** [comment]
This is an issue with how I have multiple account support setup currently.  I store the credentials based off of the email address, but the cookies file is only everything before the `@`.  I didn't expect people to have the same email on multiple domains.
