### ISSUE TITLE
Internal Server Error 500 

### ISSUE THREAD

**Issue by Elf-1** [hunterjm/futgui#41]
I'm having the same problem with the Internal Server Error (500) as efereti. I checked the WebApp and I can access the transfer market, however when I bid on a player it always says "You have either been outbid or the item is no longer available. Your bid was not accepted." After that I don't see that anyone has bid a higher price or something.

**Comment by Noobft9** [comment]
Change the player or play some matches...

**Comment by hunterjm** [comment]
EA has multiple type of temp bans.  You can be banned on Searching, Bidding, Listing, or all 3.  Try doing all of them in the web app.  If you can't do one of them, it's a temp ban.  Try again in 24 hours.

**Comment by Elf-1** [comment]
Oke thanks I will test this out, how can I prevent a temp ban to happen again?

**Comment by hunterjm** [comment]
Reduce your RPM or don't run the program for so long.
