### ISSUE TITLE
Endless loop when players are stuck in transfer target list

### ISSUE THREAD

**Issue by Fotospecht** [hunterjm/futgui#43]
I can't move some won items to the tradepile, they are stuck somehow due to an internal error. The Webapp also throws an error. This is a nasty bug of EA than can happen now and then. It will take some time until EA clears these faulty items out of the lists.

The problem is that the autobidder is caught in an endless loop and is not bidding anymore, see the log below. Could you modify the code in bid.py to ignore this error and make the program more robust ?

2015-12-23 11:20:07    Updating watched items...
2015-12-23 11:20:15    Auction Won: 700 on Lionel Messi
2015-12-23 11:20:27    Error: Lionel Messi could not be placed in the tradepile...
2015-12-23 11:20:46    Updating watched items...
2015-12-23 11:20:53    Auction Won: 700 on Lionel Messi
2015-12-23 11:21:04    Error: Lionel Messi could not be placed in the tradepile...
2015-12-23 11:21:50    Updating watched items...
...

**Comment by Fotospecht** [comment]
And of course I didn't win Messi for 700 - this was just an example :-)

**Comment by hunterjm** [comment]
It's not really in an endless loop.  It's still searching auctions, but hasn't found any.  That's why there is so much time between the error and the next "Updating watched items...".  This is likely a temp ban on listing players.  Give it 24 hours and let me know if the problem still persists after that.

**Comment by Fotospecht** [comment]
You are right, it is still bidding. But it is not a temp ban, because I tested the functionality in the Webapp.
It is definitely a stuck player. Thanks for the clarification and the nice program, and merry Xmas for you and your family.

**Comment by Fotospecht** [comment]
Hi Jason,

could you release a new version of the autobuyer Mac dmg-version with the latest 2 commits from december ?
I tried to compile it but I’m getting errors on my Mac during the build process.

Regards,
    Stefan.
