### ISSUE TITLE
Setting price but doesn't bid

### ISSUE THREAD

**Issue by maximebriand** [hunterjm/futgui#45]
i set up the automatic price to 100% (so it should buy a lot) but it doesn't bid.
It ran during 2 complete days without any bid

Is there something that can block biding? 

tested on the last release v0.7.2  on Mac with a new account but where i can access to the Transfert Martket

**Comment by Faruk-S** [comment]
Check "min credits" or "max players"

**Comment by maximebriand** [comment]
Hey thanks,

Min $ is set to 0 (as i saw it could be a solution) and max players is set to 3 (as the number of player found)
I choose a player at 200 credit to be sure and it doesn't work even if i got more than 1900 credits 

http://screencast.com/t/QOEYJkeQ4QJf

**Comment by Faruk-S** [comment]
I'm not sure but set min $ 10~100, max players 10~30  (this is about trade pile capacity not players you want to buy) and be sure there is not any non player cards in trade pile.

**Comment by maximebriand** [comment]
Thank you so much!
i didn't thought i shouldn't have non player card in my trading list

its working well now!
