### ISSUE TITLE
Underselling

### ISSUE THREAD

**Issue by erhangunay** [hunterjm/futgui#57]
First of all i would like to thank you for your work. It is AWESOME.

I would like to kindly request for an option not to undersell. Because if the price of a player is 4000 for average and while checking the prices, if someone lists for 1000 then the price is adjusted according to that. Which causes serious loss.

Additionally is it possible to have a log of the bought and selling bin s to see the profit ?

**Comment by hunterjm** [comment]
In order to prevent underselling, check the "Relist Same Price" setting.  This will ensure that we never list lower than what you bought it for.
