### ISSUE TITLE
Debian make file?

### ISSUE THREAD

**Issue by aagten** [hunterjm/futgui#58]
Hi,
I have used your excellent program for windows, but I would like to use it on another machine which is running Ubuntu 14 LTS. Can you show me the make file for Debian or how to configure it myself? Thanks.

**Comment by hunterjm** [comment]
I don't have a Debian machine to test on, but you can always run from the source if you have python3 installed.  Just install all of the requirements with `pip install -r requirements.txt` and run `python "FIFA 16 Auto Buyer.py"`
