### ISSUE TITLE
Crash with 1.0.1

### ISSUE THREAD

**Issue by Fotospecht** [hunterjm/futgui#62]
On my Macbook after starting to bid, the following log is displayed:

2016-09-30 10:57:40    Set Bid Options...
2016-09-30 10:57:42    Started bidding...
2016-09-30 10:57:42    Updating Prices for Player List...
2016-09-30 10:57:42    This is going to take around 4.2 minute(s)...

Then the program crashes with this report:

**\* Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 0]'
terminating with uncaught exception of type NSException
abort() called

**Comment by Fotospecht** [comment]
Contact me by email if you need an account for tests.

**Comment by hunterjm** [comment]
The CALayerInvalidGeometry error still comes up, but doesn't crash the program in the latest release [v1.1.0](https://github.com/hunterjm/futgui/releases/tag/v1.1.0).  Other issues should be fixed though.  Thanks for the test account!
