### ISSUE TITLE
I do not know if this working

### ISSUE THREAD

**Issue by JON-GAMES** [hunterjm/futgui#66]
I do not know if this working, I left running for a few hours and did not make any purchase.
The money is zeroing every research wrist. The cards that were listed in the transfer through PS4 or Webapp are with all zero values ​​in the list.
Congratulations on software is excellent, since the use fifa 16. I am amateur in programming, unfortunately I can only help with small donations through PayPal

**Comment by hunterjm** [comment]
Fixed in the latest release [v1.1.0](https://github.com/hunterjm/futgui/releases/tag/v1.1.0).  I didn't have an account to test with until today.
