### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by ahmad1100a** [hunterjm/futgui#71]
Hello,
I got an error whenever I tried to login ( PC - Origin)
![screenshot_20161002001927](https://cloud.githubusercontent.com/assets/22566887/19017101/63f225c8-8837-11e6-9bf8-3deafa8651ea.png)

**Comment by JON-GAMES** [comment]
I also am having the same problem. (PS4) v1.1.1

**Comment by Ghost142002** [comment]
I also am having the same problem.

**Comment by hunterjm** [comment]
Should be fixed if you re-download the windows file.
