### ISSUE TITLE
What should I put in the line access code?

### ISSUE THREAD

**Issue by Ghost142002** [hunterjm/futgui#72]
Hi, I'm new to this site. I downloaded the latest verisione of 'autobuyer of fifa 17 but I'm not enter because he says that the code is wrong. What should I put in the line access code? Sorry but I am a beginner in these things.

**Comment by hunterjm** [comment]
Leave blank first time around, then it's the code EA emails you.

**Comment by Ghost142002** [comment]
Thanks
