### ISSUE TITLE
Why AttributeError tells me: 'NoneType' object has no attribute 'group'?

### ISSUE THREAD

**Issue by Ghost142002** [hunterjm/futgui#74]
You can explain how this autobuyer? Sorry but I am a beginner.

**Comment by Ghost142002** [comment]
please can you answer me

**Comment by hunterjm** [comment]
Download the Windows binary again.  Should be fixed now.

Also, be patient, I do have a life outside of providing free software.  Creating a ticket, then following up 2 hours later (in the early hours of the morning where I live) I consider to be very rude.
