### ISSUE TITLE
 Why when I start to buy players you tell me so in the console?

### ISSUE THREAD

**Issue by Ghost142002** [hunterjm/futgui#75]
![image](https://cloud.githubusercontent.com/assets/22567489/19022467/b912efea-88d9-11e6-854c-c3cf60b49144.png)

Is it a normal thing?

**Comment by hunterjm** [comment]
Are you logged out on your console?  You can't have both running at the same time.

**Comment by Padrino02** [comment]
I have the same Error:

`Process Process-1:
Traceback (most recent call last):
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 254, in _bootstrap
  File "c:\users\jason\appdata\local\programs\python\python35-32\lib\multiproces
sing\process.py", line 93, in run
  File "C:\Users\Jason\Documents\GitHub\futgui\core\bid.py", line 50, in bid
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 679, in watchlist

  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 448, in __get__
  File "C:\Users\Jason\Documents\GitHub\futgui\api\delayedcore.py", line 42, in
__request__
  File "C:\Users\Jason\Documents\GitHub\fut\fut\core.py", line 440, in __request
__
fut.exceptions.UnknownError: {'code': '494', 'reason': '', 'string': '', 'debug'
: ''}`

And yes, I am loged out of Origin and Ultimate Team.

**Comment by cpbenny** [comment]
Hello, 

I got the same error.
I'm logged out on my console (otherwise you throw the multiplesession exception ofc)
What could cause this issue?

I get the same error in the console, but when I check 'auto update' 
UnknownError: None ({'debug': '', 'code': '494', 'reason': '', 'string': ''})
appeares in the application itself. (the 'console' of the application)

thanks!

**Comment by cpbenny** [comment]
![bug](https://cloud.githubusercontent.com/assets/22616099/19075066/94fc1328-8a43-11e6-9d8f-fb0fe92ccd8b.png)

**Comment by cpbenny** [comment]
I was thinking this had something to do with the transfer list, but this one is empty.

**Comment by cpbenny** [comment]
I'm checking  the code for a while know,  I cannot find the answer for this problem.
Anyone an idea?

**Comment by cpbenny** [comment]
The request header is too large (status code 494)

**Comment by cpbenny** [comment]
is this a client problem?

**Comment by cpbenny** [comment]
does anyone know a solution for this or what could be the problem? since this is not a frequent appearing problem (but i got it on windows and mac for my account)

**Comment by hunterjm** [comment]
This is the response sent back from EA.  I don't know what code 494 is.  Will need to look into further (maybe google around and let me know if you find anything).

**Comment by cpbenny** [comment]
It is a client error (that's for sure ;-) )

494 is deprecated but means the same as 431: This is returned when a single header field, or all of them collectively, is too large for the server to process.

**Comment by hunterjm** [comment]
These aren't HTTP status codes, they are from EA.  Looking at this issue (https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/287), it seems 494 means that your account isn't transfer market enabled on the webapp.

Make sure you able to login and access the transfer market at https://www.easports.com/fifa/ultimate-team/web-app
