### ISSUE TITLE
Self Compiled - Cant Login

### ISSUE THREAD

**Issue by kkentam** [hunterjm/futgui#78]
I got this error Message when i use my compiled version. But it works if i using your binary windows version.

AttributeError: 'NoneType' object has no attribute 'group'

Detail:
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\UserName\appdata\local\programs\python\python35-32\lib\tkinter__init__.py", line 1549, in **call**
    return self.func(*args)
  File "D:\Software_FIFA17-Autobuyer\Source\futgui-1.1.1\frames\login.py", line126, in login
    self.controller.api = DelayedCore(self.username.get(), self.password.get(),
    self.secret.get(), self.platform.get(), self.code.get(), emulate, False, cookies_file)
  File "D:\Software_FIFA17-Autobuyer\Source\futgui-1.1.1\api\delayedcore.py", line 15, in **init**
    super(DelayedCore, self).**init**(email, passwd, secret_answer, platform, code, emulate, debug, cookies)
  File "c:\users\UserName\appdata\local\programs\python\python35-32\lib\site-packages\fut\core.py", line 145, in **init**
    self.**login**(email, passwd, secret_answer, platform, code, emulate)
  File "D:\Software_FIFA17-Autobuyer\Source\futgui-1.1.1\api\delayedcore.py", line 31, in **login**
    result = super(DelayedCore, self).**login**(email, passwd, secret_answer, platform, code, emulate)
  File "c:\users\UserName\appdata\local\programs\python\python35-32\lib\site-packages\fut\core.py", line 256, in **login**
    self.nucleus_id = re.search("var EASW_ID = '([0-9]+)';", rc).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by hunterjm** [comment]
It looks like your dependencies are out of date.

**Comment by kkentam** [comment]
so strange. I was already use 3.5.2 Python to compile

**Comment by hunterjm** [comment]
The python version doesn't affect the libraries that this depends on.  try doing a `pip install --upgrade -r requirements.txt`

**Comment by kkentam** [comment]
um.............I tried..............but still failed ..............
I was failed in the pillow install process.

`      File "X:\temp\pip-build-jz5csity\Pillow\setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

    ----------------------------------------
Command "c:\users\UserName\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='X:\\temp\\pip-build-jz5csity\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record X:\temp\pip-iqsz2o1y-record\install-record.txt --single-version-externally-managed --compile" failed with errorcode 1 in X:\temp\pip-build-jz5csity\Pillow\`

**Comment by kkentam** [comment]
If i install pillow=3.3.0, it has no error..............but tried compile again, still got error
"AttributeError: 'NoneType' object has no attribute 'group'"

**Comment by kkentam** [comment]
Finally, successful to run "pip install --upgrade -r requirements.txt"
But tried compile again, still got error
"AttributeError: 'NoneType' object has no attribute 'group'"

any suggestion? Thanks

**Comment by hunterjm** [comment]
Try a `pip uninstall fut` and then run the install again.

then you can run it without building with `python 'FIFA 17 Auto Buyer.py'` to test

**Comment by kkentam** [comment]
Yes, It's work without building.....................How come??

**Comment by kkentam** [comment]
Thanks, Jason
Finally, I success to build and compile ~~~ It seems the pyinstaller problem. 
I upgrade the pyinstaller into the latest git version
https://github.com/pyinstaller/pyinstaller/archive/develop.zip

Really thanks, learn more about python today~~~

**Comment by hunterjm** [comment]
no problem!
