### ISSUE TITLE
Autobuyer Question

### ISSUE THREAD

**Issue by JonasPap** [hunterjm/futgui#80]
A friend of mine is working on an Autobuyer aswell. It works so far, but he has the problem that he get kicked out of the wb app after the autobuyer searched for like 15 minutes. Is there a possibility to fix that?
I would be awesome if you could help us/him

**Comment by hunterjm** [comment]
You need to limit the amount of requests that you are making.  They throttle it pretty heavily.  Mine is a configuration option for `RPM`.  15 requests/min is safe, but you can increase it depending on how long you are running the program for.

**Comment by JonasPap** [comment]
He is working with ca. 20 RPM and then it gets caught. Could it work if do the 20 RPM but let it pause every 5 Minutes for 30sec-1 Min?
