### ISSUE TITLE
Application wont open on Mac

### ISSUE THREAD

**Issue by ghost** [hunterjm/futgui#81]
I try to open the application, from version 1.0.1. to the newest release 1.1.1. I does just not open in Mac 10.11.6. Application "bounces" a few times, then error report can be generated.

**Comment by ghost** [comment]
Do you want me to post or PN you crash report?

**Comment by ghost** [comment]
I tried to run from dock bar, but it also does not open

**Comment by ghost** [comment]
I loved the app for Fifa 16, would like to use again for Fifa 17.

I tried install it on another Mac, also crashes at startup. Can we work on this error? How can I provide the crash report?

**Comment by hunterjm** [comment]
Duplicate of https://github.com/hunterjm/futgui/issues/67.  See there for temporary work around running from source.
