### ISSUE TITLE
Problem when running "FIFA 17 Auto Buyer.py"

### ISSUE THREAD

**Issue by stijnbastiaansen** [hunterjm/futgui#85]
Hello,

First I want of all I want to thank you for making this awesome software.

But I have got a problem, when I am trying to run FIFA 17 Auto Buyer the window disappears immediatly. I can't see what is on the screen.

Could you help me please?

**Comment by hunterjm** [comment]
That's an issue with Tkinter.  If you click the icon in your dock bar at the bottom it should pop up.

**Comment by stijnbastiaansen** [comment]
I am running it on windows, but the icon also dissapears immediatyly. 
I have followed [this tutorial ](https://github.com/hunterjm/futgui/issues/16)
Did I something wrong?

**Comment by captcrywolf** [comment]
i am facing the same issue , please help , i dont know how to use python,

**Comment by stijnbastiaansen** [comment]
I forgot to do this, if you do this you will get your bot to work.

---

Requirements

This has only been tested and built with Python 3.5.

pip install -r requirements.txt
Build (Mac):

make macbundle
Build (Windows):

Make sure to delete build and dist folders before re-building.

pyinstaller '.\FIFA 17 Auto Buyer.spec'

**Comment by darfinx** [comment]
https://github.com/hunterjm/futgui/releases
download program which is compatible your os. 

Get Outlook for iOS

On Mon, Oct 17, 2016 at 10:14 AM +0300, "stijnbastiaansen" notifications@github.com wrote:

I forgot to do this, if you do this you will get your bot to work.

Requirements

This has only been tested and built with Python 3.5.

pip install -r requirements.txt

Build (Mac):

make macbundle

Build (Windows):

Make sure to delete build and dist folders before re-building.

pyinstaller '.\FIFA 17 Auto Buyer.spec'
