### ISSUE TITLE
internalservererror (500)

### ISSUE THREAD

**Issue by yousufm5** [hunterjm/futgui#94]
Every time i start bidding i get the message internalservererror (500).

I'm just wondering how to fix this errors this autobidder no longer works.
Any suggestions ?!

**Comment by darfinx** [comment]
i have same situtation. i can bid, buy, list search visa webapp. i think i am not temp ban or something like this.

**Comment by Mglt-b** [comment]
change emulation type at running (ios/android/pc) resolve the problem..

i think is a soft ban (temp), but only for a plateform

change emulation resolve the problem, until you're temp ban on 3 plateform

**Comment by hunterjm** [comment]
That is correct. Temp bans are only for the emulation type.
