### ISSUE TITLE
Best settings?

### ISSUE THREAD

**Issue by xhaize** [hunterjm/futgui#96]
Whats are the best settings to sell the players faster?

**Comment by aftershock9** [comment]
It varies depending on factors:
- Type of player
- Popularity of the league
- Card weight

etc.

My suggestion is to create a spreadsheet and track the players you use on the bot. With the feature that jason has introduced with the won column, you can see which players are bought often.

**Comment by hunterjm** [comment]
Play around with different settings and players. The default settings are the "safe" settings. That will pretty much guarantee a profit when used with players worth 1-2k. A bunch of small profits > sitting on a player for days trying to make a big profit.
