### ISSUE TITLE
Quit unxpectedly - MAC

### ISSUE THREAD

**Issue by fi8471** [hunterjm/futgui#98]
mac version quits unexpectedly every time i try to use it. I manage to log in but get no further.

**Comment by JKetelaar** [comment]
Same here.
Error-log: https://gist.github.com/JKetelaar/30224463d3e039a5d523bec2c1156e9c

**Comment by hunterjm** [comment]
Duplicate of https://github.com/hunterjm/futgui/issues/67.  See there for temporary work/around by running from source code.
